### PR TITLE
Unit Testing

### LINKED ISSUE #21: Add unit tests
Add unit tests for the script

### PR DESCRIPTION
**Pull request by modelmat**
Fixes #21 

Also added another image from https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/OCR-A_sample.svg/1280px-OCR-A_sample.svg.png

### CODE REVIEW

**Comment by modelmat** [comment]
Oops, apparently forgot to push some things. Don't merge this yet.

(this was designed for pytest)

**Comment by Yajan** [comment]
I will try creating unit tests with mock object for os module.

**Comment by prabhakar267** [comment]
@Modelmat since someone else claimed the issue before you raised a PR
I am closing this PR
Please feel free to add more unit tests once #23  is merged!

**Comment by modelmat** [comment]
I didn't know you had to send a message to claim it?
I'd been working on it for a while and hadn't sent a message?

**Comment by modelmat** [comment]
I'll add the tests into the already commited though.

**Pull request closed without merging**
